<x-coach-chat
    icon="user-group"
    avatar-gradient="bg-gradient-to-br from-indigo-400 to-violet-500"
    avatar-shadow="shadow-lg shadow-indigo-500/25"
    avatar-shadow-small="shadow-md shadow-indigo-500/20"
    avatar-shadow-large="shadow-xl shadow-indigo-500/30"
    subtitle-color="text-indigo-600 dark:text-indigo-400"
    bubble-bg="bg-indigo-50/50 dark:bg-indigo-950/20"
    bubble-border="border-indigo-200/50 dark:border-indigo-800/30"
    suggestion-colors="bg-indigo-100 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 hover:bg-indigo-200 dark:hover:bg-indigo-900/50"
    title="Team Coach"
    :subtitle="$team?->name ?? ''"
    back-route="admin.matrix"
    :welcome-heading="'Team Coach for ' . ($team?->name ?? '')"
    welcome-description="I can help you understand your team's skills, spot gaps before they become problems, and suggest who could mentor whom."
    placeholder="Ask about your team's skills..."
    :suggestions="['What are our biggest skill gaps?', 'Who could mentor someone in Kubernetes?', 'Any single points of failure?', 'Show me recent team activity']"
    :messages="$messages"
    :disabled="!$team"
    disabled-heading="No team to coach"
    disabled-description="You don't manage any teams yet. Contact an admin to set up your team."
    :mode="\App\Enums\CoachMode::Team"
    :team-id="$teamId"
    :conversation-id="$conversationId"
    :pending-prompt="$pendingPrompt"
/>
