<x-coach-chat
    icon="sparkles"
    color="amber"
    gradient-from="amber-400"
    gradient-to="orange-500"
    title="Skills Coach"
    subtitle="Here to help you connect"
    back-route="home"
    welcome-heading="Hey, I'm your Skills Coach"
    welcome-description="I know the team pretty well. Ask me about skills to learn, and I'll point you to the people who can actually help — real colleagues, not just courses."
    placeholder="Ask me about your skills..."
    :suggestions="['What should I learn next?', 'Who else knows Kubernetes?', 'Help me level up in Python', 'What\'s trending on the team?']"
    :messages="$messages"
    :mode="\App\Enums\CoachMode::Personal"
    :conversation-id="$conversationId"
    :pending-prompt="$pendingPrompt"
/>
